language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: osx
      compiler: clang
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - echo $LANG
  - echo $LC_ALL
  - eval "${MATRIX_EVAL}"
  - ./scripts/travis/before_install.sh

install:
  - ./scripts/travis/install.sh
  - if [ $TRAVIS_OS_NAME == linux ]; then source /opt/qt56/bin/qt56-env.sh; fi

before_script:
  - cmake --system-information info.txt && cat info.txt
  - cmake .

script:
  - VERBOSE=1 make -j2
  - ./bin/tests
