# Not using "cpp" because the default tools are so old!
language: generic

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8

    - os: osx
      compiler: clang
      osx_image: xcode11.3
      env:
        - CC=clang
        - CXX=clang++

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $CC
  - echo $CXX
  - ./scripts/travis/before_install.sh

install:
  - ./scripts/travis/install.sh

before_script:
  - cmake --system-information info.txt && cat info.txt
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON ..

script:
  - VERBOSE=1 make -j2 && ./bin/tests
