# Not using "cpp" because the default tools are so old!
language: generic

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: osx
      compiler: clang
      osx_image: xcode11.3
      env:
        - CC=clang
        - CXX=clang++

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $CC
  - echo $CXX
  - ./scripts/travis/before_install.sh

install:
  - ./scripts/travis/install.sh

before_script:
  - ./scripts/travis/cmake.sh

script:
  - ./scripts/travis/run.sh
